version: "3"
services: 
  goapp: # サービス名
    build: # ビルドに使うDockerファイルのパス
      context: .
      dockerfile: ./Dockerfile
    tty: true # コンテナの永続化
    volumes:
      - ./:/go/pkg/mod/github.com/yamadatt/movabletype # マウントディレクトリ


